# -*- coding: utf-8 -*-
"""Student Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTVDad5inLO6MEPk6FpiZBBe_CC_BHFZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Expanded_data_with_more_features.csv")
df.head()

df.describe()

df.info()

"""***Checking for total number of null values in each column***"""

df.isnull().sum()

"""***Drop Unnamed Column***"""

df = df.drop("Unnamed: 0", axis = 1)
df.head()

"""***Gender distribution***"""

plt.figure(figsize = (5,5))
ax = sns.countplot(data = df, x = "Gender", palette="viridis")
ax.bar_label(ax.containers[0])
plt.show()

"""***Conclusion: From above chart we analyzed that: Number of females are more then number of males.***

***Parent Education role in Students Marks***
"""

gb = df.groupby("ParentEduc").agg({"MathScore":'mean', "ReadingScore":'mean', "WritingScore":'mean'})
gb

plt.figure(figsize = (5,5))
sns.heatmap(data = gb, annot = True)
plt.title("Relationship between Parents Education vs Students Score ")
plt.show()

"""***Conclusion: In above char we concluded that: Education of parents have good impact on students score.***

***Role Parents Maritial Status in Student education***
"""

gb1 = df.groupby("ParentMaritalStatus").agg({"MathScore":'mean', "ReadingScore":'mean', "WritingScore":'mean'})
gb1

plt.figure(figsize = (5,5))
sns.heatmap(data = gb1, annot = True)
plt.title("Relationship between Parents Maritial Status vs Students Score ")
plt.show()

"""***Conclusion: From above heatmap we can conclude that: there is no impact of student score based on their parents maritial status.***

***To Findout Outliers***
"""

plt.figure(figsize = (5,5))
sns.boxplot(data = df, x = "MathScore")
plt.show()

plt.figure(figsize = (5,5))
sns.boxplot(data = df, x = "ReadingScore")
plt.show()

plt.figure(figsize = (5,5))
sns.boxplot(data = df, x = "WritingScore")
plt.show()

print(df["EthnicGroup"].unique())

"""***Distribution of Ethinic Groups***"""

groupA = df.loc[(df['EthnicGroup']=="group A")].count()
groupB = df.loc[(df['EthnicGroup']=="group B")].count()
groupC = df.loc[(df['EthnicGroup']=="group C")].count()
groupD = df.loc[(df['EthnicGroup']=="group D")].count()
groupE = df.loc[(df['EthnicGroup']=="group E")].count()

labe = ["group A", "group B","group C","group D","group E"]
mlist = [groupA["EthnicGroup"], groupB["EthnicGroup"], groupC["EthnicGroup"], groupD["EthnicGroup"], groupE["EthnicGroup"]]

plt.figure(figsize = (5,5))
plt.pie(mlist, labels = labe, autopct = "%1.2f%%")
plt.title("Distribution of Ethinic Groups")
plt.show()

"""***Count of Ethnic Group***"""

plt.figure(figsize=(5,5))
ax = sns.countplot(data = df, x = "EthnicGroup", palette="viridis")
ax.bar_label(ax.containers[0])
plt.show()

"""***Study hours vs Maths Score***"""

plt.figure(figsize=(5,5))
sns.boxplot(data=df,x='WklyStudyHours',y='MathScore', palette="viridis")
plt.xlabel('Weekly Study Hours')
plt.ylabel('Math Score')
plt.title('Box Plot Outlier for Study Hours')
plt.show()

"""***Conclusion: From above box plot we came to know that:Student who studied for more then 10hr per week got 0 marks in maths***"""